name: Docker Build

on:
  push:
    branches: [ "main" ]   # Run workflow whenever you push to main

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub provides a Linux VM
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Pulls your repo code into the VM

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2   # Prepares Docker builder

      - name: Build Docker image
        run: docker build -t devops-hello .
